server:
  port: 8084

spring:
  application:
    name: cart-service
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12306/eureka

hp:
  jwt:
    pubKeyPath: C:\Users\zy\Desktop\project\tmp\rsa\rsa.pub #公钥地址