server:
  port: 8087

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12306/eureka


hp:
  jwt:
    secret: as*&ka^23$lpifqnGOQ#ao%alhaipi #登录校验的密钥
    pubKeyPath: C:\Users\zy\Desktop\project\tmp\rsa\rsa.pub #公钥地址
    priKeyPath: C:\Users\zy\Desktop\project\tmp\rsa\rsa.pri #私钥地址
    expire: 30 #过期时间 ，单位分钟