server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///haipi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 8190972
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:12306/eureka

#日志打印sql语句
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
     com.haipi: debug

